title: Bianca Pereira
description: Blog

url: http://bianca-pereira.github.io
baseurl: "http://bianca-pereira.github.io/blog"
paginate_path: "page:num/"
permalink: :title/

markdown: kramdown
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Blog
   url: /blog
 - title: Publications
   url: /publications.html
 - title: Contact
   url: /contact.html

social:
   github: bianca-pereira
   twitter: bianca_oli_per
   facebook: bianca.oli.pereira
   email: bianca@biancapereira.me

#google_analytics: "UA-66654253-1"