title: Bianca Pereira
description: Blog

url: http://bianca-pereira.github.io
baseurl: "http://bianca-pereira.github.io/blog"
paginate_path: "page:num/"
permalink: :title/

markdown: kramdown
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Blog
   url: /blog
 - title: Publications
   url: /publications/index.html
 - title: Contact
   url: /contact/index.html

social:
   ggithub: bianca-pereira
   twitter: bianca_oli_per
   facebook: Bianca-Pereira-978301655573527
   email: bianca@biancapereira.me
   linkedin: biancaolipereira
   soundcloud: user-671615919
   quora: Bianca-Pereira-7

google_analytics: "UA-66654253-1"